version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/myapp:z
      - gems:/usr/local/bundle
    env_file:
      - docker/env.web
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  db:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: salt_edge
  redis:
    platform: linux/amd64
    image: 'redis:6.2.12-alpine'
    command: 'redis-server'
    volumes:
      - redis:/var/lib/redis/data
  sidekiq:
    build: .
    command: 'bash -c "bundle && bundle exec sidekiq -C config/sidekiq.yml"'
    volumes:
      - .:/myapp:z
      - gems:/usr/local/bundle
    env_file:
      - docker/env.web
    depends_on:
      - db
      - redis
volumes:
  db_data: {}
  redis: {}
  gems: {}
